# Generated by Django 3.2 on 2023-04-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0002_auto_20230423_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='media/Images/'),
        ),
    ]
