# Generated by Django 3.2 on 2023-04-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0003_alter_clothing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='Images/'),
        ),
    ]
