# Generated by Django 3.2 on 2023-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0004_alter_clothing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolder', models.CharField(default='', max_length=500)),
                ('cardNumber', models.IntegerField(max_length=16)),
                ('expDate', models.DateField(auto_now_add=True)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
