# Generated by Django 3.2 on 2023-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(),
        ),
    ]
