# Generated by Django 3.2 on 2023-04-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0006_auto_20230427_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expDate',
            field=models.DateField(),
        ),
    ]
