# Generated by Django 3.2 on 2023-04-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0007_alter_payment_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardHolder',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
