# Generated by Django 3.2 on 2023-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0008_alter_payment_cardholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
