# Generated by Django 3.2 on 2023-04-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesimulatte', '0009_payment_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
